global:
  scrape_interval: 1m
  scrape_timeout: 10s
scrape_configs:
  - job_name: MY_JOB
    sample_limit: 10000
    ec2_sd_configs:
      - region: us-east-1
        port: 9404
        filters:
          - name: tag:aws:autoscaling:groupName
            values:
              - liquid-stg-us-east-2-monitoring_asg 
